# 数据源配置
spring:
    datasource:
        dynamic:
            primary: master #设置默认的数据源，默认值为master
            strict: false
            datasource:
                # 主库数据源
                master:
                    url: jdbc:mysql://1.92.74.70:3306/mm_sys?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    username: big_data
                    password: fdHpcXJgQiR8EOdN
                # 从库数据源
                slave:
                    url: jdbc:mysql://1.92.74.70:3306/mm_daas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    username: big_data
                    password: fdHpcXJgQiR8EOdN

